### ISSUE TITLE
ZCU216-PYNQ

### ISSUE THREAD

**Issue by KAUSHAL1986** [Xilinx/ZCU111-PYNQ#31]
Can anybody list the detailed steps for creating this repository for ZCU216 kit ....

**Comment by schelleg** [comment]
I'll close this now due to duplicate thread on strath-sdr.  Feel free to raise issue on discuss.pynq.io as well where we track support requests.

**Comment by KAUSHAL1986** [comment]
Please reopen this issue... For the link you have mentioned it is not a duplicate thread.. that is another issue...

and please do mention the steps to proceed for ZCU216 kit... 

I request  @PeterOgden to please help me out on this one....

**Comment by schelleg** [comment]
Hi @KAUSHAL1986 - This repo is only for hosting the board files to build the ZCU111 PYNQ image ... your request is about the ZCU216 board ... we don't have steps "to proceed for ZCU216 kit".   But this is all open-source, so let us know any specific questions on the forum.  It probably won't get answered here is all I'm saying.

And requesting support is possible if you're a Xilinx customer - let us know your use case and if you have a contact inside Xilinx.  Otherwise, the forum is your best bet to find answers.
